import { RED } from "./constants";

export const S = {
  body: { background: "#0a0a0a", color: "#f2ede6", fontFamily: "Georgia,serif", minHeight: "100vh" },
  header: { borderBottom: "1px solid #333", display: "flex", alignItems: "stretch" },
  hleft: { padding: "1.8rem 2rem", borderRight: "1px solid #333", flex: 1, cursor: "pointer", userSelect: "none" },
  tagline: { marginTop: "0.5rem", fontSize: "0.68rem", letterSpacing: "0.18em", color: "#888", fontFamily: "monospace" },
  hright: { padding: "1.8rem 2rem", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "flex-end", gap: "0.55rem", minWidth: 150 },
  navBtn: { color: "#888", fontSize: "0.7rem", letterSpacing: "0.15em", cursor: "pointer", background: "none", border: "none", fontFamily: "monospace", padding: 0, textAlign: "right" },
  navActive: { color: RED },
  ticker: { background: RED, color: "#f2ede6", padding: "0.3rem 0", overflow: "hidden", whiteSpace: "nowrap" },
  tickerSpan: { display: "inline-block", fontSize: "0.65rem", letterSpacing: "0.16em", animation: "kaosticker 30s linear infinite", fontFamily: "monospace" },
  main: { padding: "2.5rem 2rem", maxWidth: 1100, margin: "0 auto" },
  sh: { display: "flex", alignItems: "center", gap: "1rem", marginBottom: "1.8rem" },
  st: { fontSize: "0.68rem", letterSpacing: "0.28em", textTransform: "uppercase", color: "#888", whiteSpace: "nowrap", fontFamily: "monospace" },
  sl: { flex: 1, height: 1, background: "#333" },
  alist: { border: "1px solid #333", marginBottom: "2.5rem" },
  arow: { display: "grid", gridTemplateColumns: "90px 1fr auto", alignItems: "center", gap: "1.2rem", padding: "1.3rem 1.8rem", cursor: "pointer", background: "transparent", transition: "background 0.2s" },
  adate: { fontSize: "0.6rem", color: "#555", lineHeight: 1.5, fontFamily: "monospace" },
  atitle: { fontSize: "0.95rem", fontWeight: 700, color: "#f2ede6", lineHeight: 1.4 },
  asmall: { display: "block", fontFamily: "monospace", fontSize: "0.68rem", fontWeight: 400, color: "#777", marginTop: "0.25rem" },
  atag: { fontSize: "0.58rem", letterSpacing: "0.15em", textTransform: "uppercase", color: RED, whiteSpace: "nowrap", fontFamily: "monospace" },
  ared: { border: "1px solid " + RED, padding: "2.2rem", marginBottom: "2.5rem" },
  aredH: { fontSize: "1.4rem", marginBottom: "1rem", color: RED },
  aredP: { fontSize: "0.86rem", lineHeight: 1.95, color: "#ccc" },
  artWrap: { maxWidth: 740 },
  backBtn: { display: "inline-flex", alignItems: "center", gap: "0.4rem", fontSize: "0.65rem", letterSpacing: "0.15em", textTransform: "uppercase", color: "#888", cursor: "pointer", marginBottom: "2.2rem", background: "none", border: "none", fontFamily: "monospace", padding: 0 },
  artTag: { fontSize: "0.6rem", letterSpacing: "0.22em", textTransform: "uppercase", color: RED, marginBottom: "1rem", display: "block", fontFamily: "monospace" },
  artTitle: { fontSize: "clamp(1.6rem,3.5vw,2.6rem)", fontWeight: 700, lineHeight: 1.15, marginBottom: "0.9rem" },
  artMeta: { fontSize: "0.65rem", color: "#888", borderBottom: "1px solid #333", paddingBottom: "1.3rem", marginBottom: "2.2rem", fontFamily: "monospace" },
  artBody: { fontSize: "0.93rem", lineHeight: 2.05, color: "#ccc" },
  artP: { marginBottom: "1.5rem" },
  pull: { borderLeft: "3px solid " + RED, padding: "0.8rem 0 0.8rem 1.6rem", margin: "2rem 0", fontStyle: "italic", fontSize: "1.1rem", lineHeight: 1.65, color: "#ddd" },
  agrid: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: "2rem", marginBottom: "2.5rem" },
  abox: { border: "1px solid #333", padding: "2.2rem" },
  aboxH: { fontSize: "1.2rem", marginBottom: "1rem" },
  aboxP: { fontSize: "0.82rem", lineHeight: 1.9, color: "#aaa" },
  footer: { borderTop: "1px solid #333", padding: "1.5rem 2rem", maxWidth: 1100, margin: "0 auto", display: "flex", justifyContent: "space-between", alignItems: "center", fontSize: "0.6rem", color: "#444", letterSpacing: "0.15em", fontFamily: "monospace" },
};
